export const ALBUMS_SEED = [
  {
    name: 'Llegaste muy tarde',
    genre: 'Bachata',
    concept: 'Álbum de desamor: personas que no supieron valorar un amor hasta que fue demasiado tarde.',
    main_emotion: 'Desamor, arrepentimiento ajeno, cierre',
    target_audience: '22-40 años, oyentes de bachata emocional y de desamor',
    color: '#F2A7A7',
    total_songs: 11,
    album_launch_date: '2026-09-19',
    album_scheduled: false,
    album_published: false,
    youtube_url: null,
    launch_notes: null,
  },
  {
    name: 'Ya no vuelvo atrás',
    genre: 'Dancehall moderno',
    concept: 'Empoderamiento femenino: una mujer deja atrás relaciones que la apagaban y vuelve a elegirse.',
    main_emotion: 'Empoderamiento, independencia, seguridad',
    target_audience: '18-35 años, oyentes de dancehall y urbano en español',
    color: '#B5D5F5',
    total_songs: 11,
    album_launch_date: '2026-09-23',
    album_scheduled: false,
    album_published: false,
    youtube_url: null,
    launch_notes: null,
  },
  {
    name: 'Las pequeñas cosas',
    genre: 'Indie Folk',
    concept: 'Gratitud: disfrutar la vida sencilla y aprender a valorar los pequeños momentos.',
    main_emotion: 'Gratitud, calma, contemplación',
    target_audience: '25-45 años, oyentes de indie folk / lo-fi para estudiar o relajarse',
    color: '#C3E6CB',
    total_songs: 11,
    album_launch_date: '2026-09-28',
    album_scheduled: false,
    album_published: false,
    youtube_url: null,
    launch_notes: null,
  },
  {
    name: 'Volví a escucharme',
    genre: 'Power Pop / Pop Soul',
    concept: 'Crecimiento personal: recuperar tu voz y volver a creer en ti.',
    main_emotion: 'Superación, autoestima, motivación',
    target_audience: '18-35 años, oyentes de pop motivacional y soul',
    color: '#D4BBEE',
    total_songs: 11,
    album_launch_date: '2026-10-02',
    album_scheduled: false,
    album_published: false,
    youtube_url: null,
    launch_notes: null,
  },
  {
    name: 'Desde que llegaste',
    genre: 'Regional romántico',
    concept: 'Amor sano: la tranquilidad de encontrar a la persona correcta.',
    main_emotion: 'Amor sano, calma, gratitud en pareja',
    target_audience: '25-45 años, oyentes de regional romántico',
    color: '#FFD6B0',
    total_songs: 11,
    album_launch_date: '2026-10-06',
    album_scheduled: false,
    album_published: false,
    youtube_url: null,
    launch_notes: null,
  },
  {
    name: 'Vuelvo a sentir la vida',
    genre: 'Salsa',
    concept: 'Celebrar la vida, renacer y volver a sonreír.',
    main_emotion: 'Alegría, celebración, renacimiento',
    target_audience: '22-50 años, oyentes de salsa romántica y de celebración',
    color: '#FFF0A0',
    total_songs: 10,
    album_launch_date: '2026-09-15',
    album_scheduled: false,
    album_published: false,
    youtube_url: null,
    launch_notes: null,
  },
]

export const SONGS_SEED: Array<{
  album_name: string
  name: string
  track_number: number
  scheduled_date: string
  scheduled_time: string
}> = [
  { album_name: 'Llegaste muy tarde', name: 'Ahora me buscas', track_number: 1, scheduled_date: '2026-08-10', scheduled_time: '13:00' },
  { album_name: 'Ya no vuelvo atrás', name: 'Ya no vuelvo atrás', track_number: 1, scheduled_date: '2026-08-10', scheduled_time: '19:00' },
  { album_name: 'Las pequeñas cosas', name: 'El olor del café', track_number: 1, scheduled_date: '2026-08-11', scheduled_time: '13:00' },
  { album_name: 'Volví a escucharme', name: 'Volví a escucharme', track_number: 1, scheduled_date: '2026-08-11', scheduled_time: '19:00' },
  { album_name: 'Desde que llegaste', name: 'Desde que llegaste', track_number: 1, scheduled_date: '2026-08-12', scheduled_time: '13:00' },
  { album_name: 'Vuelvo a sentir la vida', name: 'Vuelvo a sentir la vida', track_number: 1, scheduled_date: '2026-08-12', scheduled_time: '19:00' },
  { album_name: 'Llegaste muy tarde', name: 'Qué te vaya bonito', track_number: 2, scheduled_date: '2026-08-13', scheduled_time: '13:00' },
  { album_name: 'Ya no vuelvo atrás', name: 'Me elegí primero', track_number: 2, scheduled_date: '2026-08-13', scheduled_time: '19:00' },
  { album_name: 'Las pequeñas cosas', name: 'Todo florece a su tiempo', track_number: 2, scheduled_date: '2026-08-14', scheduled_time: '13:00' },
  { album_name: 'Volví a escucharme', name: 'Ya no me escondo', track_number: 2, scheduled_date: '2026-08-14', scheduled_time: '17:00' },
  { album_name: 'Desde que llegaste', name: 'Contigo entendí', track_number: 2, scheduled_date: '2026-08-14', scheduled_time: '20:30' },
  { album_name: 'Vuelvo a sentir la vida', name: 'Hoy me despertó la alegría', track_number: 2, scheduled_date: '2026-08-15', scheduled_time: '13:00' },
  { album_name: 'Llegaste muy tarde', name: 'Ya no tienes dónde volver', track_number: 3, scheduled_date: '2026-08-15', scheduled_time: '19:00' },
  { album_name: 'Ya no vuelvo atrás', name: 'No me apagues', track_number: 3, scheduled_date: '2026-08-17', scheduled_time: '13:00' },
  { album_name: 'Las pequeñas cosas', name: 'La lluvia también abraza', track_number: 3, scheduled_date: '2026-08-17', scheduled_time: '19:00' },
  { album_name: 'Volví a escucharme', name: 'No era mi culpa', track_number: 3, scheduled_date: '2026-08-18', scheduled_time: '13:00' },
  { album_name: 'Desde que llegaste', name: 'Qué suerte encontrarte', track_number: 3, scheduled_date: '2026-08-18', scheduled_time: '19:00' },
  { album_name: 'Vuelvo a sentir la vida', name: 'Baila conmigo la vida', track_number: 3, scheduled_date: '2026-08-19', scheduled_time: '13:00' },
  { album_name: 'Llegaste muy tarde', name: 'Me aprendí sin ti', track_number: 4, scheduled_date: '2026-08-19', scheduled_time: '19:00' },
  { album_name: 'Ya no vuelvo atrás', name: 'Sola me queda bien', track_number: 4, scheduled_date: '2026-08-20', scheduled_time: '13:00' },
  { album_name: 'Las pequeñas cosas', name: 'El banco del parque', track_number: 4, scheduled_date: '2026-08-20', scheduled_time: '17:00' },
  { album_name: 'Volví a escucharme', name: 'Después del miedo', track_number: 4, scheduled_date: '2026-08-20', scheduled_time: '20:30' },
  { album_name: 'Desde que llegaste', name: 'Mi lugar favorito', track_number: 4, scheduled_date: '2026-08-21', scheduled_time: '13:00' },
  { album_name: 'Vuelvo a sentir la vida', name: 'Ya salió el sol', track_number: 4, scheduled_date: '2026-08-21', scheduled_time: '19:00' },
  { album_name: 'Llegaste muy tarde', name: 'Tu arrepentimiento', track_number: 5, scheduled_date: '2026-08-22', scheduled_time: '13:00' },
  { album_name: 'Ya no vuelvo atrás', name: 'Sin pedir permiso', track_number: 5, scheduled_date: '2026-08-22', scheduled_time: '19:00' },
  { album_name: 'Las pequeñas cosas', name: 'Un día cualquiera', track_number: 5, scheduled_date: '2026-08-24', scheduled_time: '13:00' },
  { album_name: 'Volví a escucharme', name: 'Todavía puedo', track_number: 5, scheduled_date: '2026-08-24', scheduled_time: '19:00' },
  { album_name: 'Desde que llegaste', name: 'Todo tiene sentido', track_number: 5, scheduled_date: '2026-08-25', scheduled_time: '13:00' },
  { album_name: 'Vuelvo a sentir la vida', name: 'Sin miedo a sonreír', track_number: 5, scheduled_date: '2026-08-25', scheduled_time: '19:00' },
  { album_name: 'Llegaste muy tarde', name: 'No era para siempre', track_number: 6, scheduled_date: '2026-08-26', scheduled_time: '13:00' },
  { album_name: 'Ya no vuelvo atrás', name: 'Bailando con mi sombra', track_number: 6, scheduled_date: '2026-08-26', scheduled_time: '17:00' },
  { album_name: 'Las pequeñas cosas', name: 'El sonido del viento', track_number: 6, scheduled_date: '2026-08-26', scheduled_time: '20:30' },
  { album_name: 'Volví a escucharme', name: 'Me debía esta canción', track_number: 6, scheduled_date: '2026-08-27', scheduled_time: '13:00' },
  { album_name: 'Desde que llegaste', name: 'Lo mejor de mis días', track_number: 6, scheduled_date: '2026-08-27', scheduled_time: '19:00' },
  { album_name: 'Vuelvo a sentir la vida', name: 'Que siga la música', track_number: 6, scheduled_date: '2026-08-28', scheduled_time: '13:00' },
  { album_name: 'Llegaste muy tarde', name: 'La última llamada', track_number: 7, scheduled_date: '2026-08-28', scheduled_time: '19:00' },
  { album_name: 'Ya no vuelvo atrás', name: 'Tú ya no decides', track_number: 7, scheduled_date: '2026-08-29', scheduled_time: '13:00' },
  { album_name: 'Las pequeñas cosas', name: 'Donde el tiempo descansa', track_number: 7, scheduled_date: '2026-08-29', scheduled_time: '19:00' },
  { album_name: 'Volví a escucharme', name: 'Mi lugar', track_number: 7, scheduled_date: '2026-08-31', scheduled_time: '13:00' },
  { album_name: 'Desde que llegaste', name: 'Eres mi calma', track_number: 7, scheduled_date: '2026-08-31', scheduled_time: '19:00' },
  { album_name: 'Vuelvo a sentir la vida', name: 'Cada paso cuenta', track_number: 7, scheduled_date: '2026-09-01', scheduled_time: '13:00' },
  { album_name: 'Llegaste muy tarde', name: 'No vuelvo a caer', track_number: 8, scheduled_date: '2026-09-01', scheduled_time: '17:00' },
  { album_name: 'Ya no vuelvo atrás', name: 'Más fuerte que ayer', track_number: 8, scheduled_date: '2026-09-01', scheduled_time: '20:30' },
  { album_name: 'Las pequeñas cosas', name: 'Las manos que conozco', track_number: 8, scheduled_date: '2026-09-02', scheduled_time: '13:00' },
  { album_name: 'Volví a escucharme', name: 'Más fuerte que mis dudas', track_number: 8, scheduled_date: '2026-09-02', scheduled_time: '19:00' },
  { album_name: 'Desde que llegaste', name: 'Si es contigo', track_number: 8, scheduled_date: '2026-09-03', scheduled_time: '13:00' },
  { album_name: 'Vuelvo a sentir la vida', name: 'La vida me encontró', track_number: 8, scheduled_date: '2026-09-03', scheduled_time: '19:00' },
  { album_name: 'Llegaste muy tarde', name: 'Te quedaste solo', track_number: 9, scheduled_date: '2026-09-04', scheduled_time: '13:00' },
  { album_name: 'Ya no vuelvo atrás', name: 'No era amor', track_number: 9, scheduled_date: '2026-09-04', scheduled_time: '19:00' },
  { album_name: 'Las pequeñas cosas', name: 'Un lugar llamado hogar', track_number: 9, scheduled_date: '2026-09-05', scheduled_time: '13:00' },
  { album_name: 'Volví a escucharme', name: 'Nunca fue demasiado tarde', track_number: 9, scheduled_date: '2026-09-05', scheduled_time: '19:00' },
  { album_name: 'Desde que llegaste', name: 'Después de ti', track_number: 9, scheduled_date: '2026-09-07', scheduled_time: '13:00' },
  { album_name: 'Vuelvo a sentir la vida', name: '¡Que nadie me pare!', track_number: 9, scheduled_date: '2026-09-07', scheduled_time: '17:00' },
  { album_name: 'Llegaste muy tarde', name: 'Llegaste muy tarde', track_number: 10, scheduled_date: '2026-09-07', scheduled_time: '20:30' },
  { album_name: 'Ya no vuelvo atrás', name: 'Libre de ti', track_number: 10, scheduled_date: '2026-09-08', scheduled_time: '13:00' },
  { album_name: 'Las pequeñas cosas', name: 'La belleza de lo simple', track_number: 10, scheduled_date: '2026-09-08', scheduled_time: '19:00' },
  { album_name: 'Volví a escucharme', name: 'Ahora sí soy yo', track_number: 10, scheduled_date: '2026-09-09', scheduled_time: '13:00' },
  { album_name: 'Desde que llegaste', name: 'Aquí quiero quedarme', track_number: 10, scheduled_date: '2026-09-09', scheduled_time: '19:00' },
  { album_name: 'Vuelvo a sentir la vida', name: '¡Qué bonito es vivir!', track_number: 10, scheduled_date: '2026-09-10', scheduled_time: '13:00' },
  { album_name: 'Llegaste muy tarde', name: 'Brindo por tu adiós', track_number: 11, scheduled_date: '2026-09-10', scheduled_time: '19:00' },
  { album_name: 'Ya no vuelvo atrás', name: 'Esta soy yo', track_number: 11, scheduled_date: '2026-09-11', scheduled_time: '13:00' },
  { album_name: 'Las pequeñas cosas', name: 'Las pequeñas cosas', track_number: 11, scheduled_date: '2026-09-11', scheduled_time: '19:00' },
  { album_name: 'Volví a escucharme', name: 'Hoy empieza todo', track_number: 11, scheduled_date: '2026-09-12', scheduled_time: '13:00' },
  { album_name: 'Desde que llegaste', name: 'Toda la vida', track_number: 11, scheduled_date: '2026-09-12', scheduled_time: '19:00' },
]
